language: scala
after_success:
- sbt publishSigned
before_install:
- openssl aes-256-cbc -K $encrypted_6f00f9548c6c_key -iv $encrypted_6f00f9548c6c_iv
  -in secring.gpg.enc -out secring.gpg -d
env:
  global:
    secure: UtCZxCKVKwXI09EZTSCsfLRcjQszGjiy6vkM+Yw/EY8SfJRVynJdLglDg6QMQYFyvT5eR2iMde6ap8P6y+mIZU/kp8tmMyBUnt6rNQG+8ECzHVpHEYrHv2MuBYuWPvuL8JkVqC9p23KQCy7WV9C/m9qDQTpx0aF2i2Bsmpypidw=
