language: scala
after_success:
- sbt publishSigned
env:
  global:
    secure: UcrUWLs+/pruprbgh/ZeZY6gum0BuV4WWIf6BeFWqm6FV5Z3EgNAdUBmULm3W9RjUYF2jYbV7UvasHMI/0wZ+uPBpL+GVdKufUMWqasstKlhTR8Ar8gd0aOGP2wJPbKIweV+dUiH5sEC2Q+Yl2oIgSDtGmXqW+Tp/adz2ATHSeo=
before_install:
- openssl aes-256-cbc -K $encrypted_6f00f9548c6c_key -iv $encrypted_6f00f9548c6c_iv -in sonatype-credentials.txt.enc -out sonatype-credentials.txt -d
- openssl aes-256-cbc -K $encrypted_6f00f9548c6c_key -iv $encrypted_6f00f9548c6c_iv -in secring.gpg.enc -out secring.gpg -d
